### ISSUE TITLE
Fix the next.js compatibility 

### ISSUE THREAD

**Issue by Divide-By-0** [zkemail/proof-of-twitter#10]
When we compile and hit verify of the locally cloned repo, it doesn't seem to run. One issue is importing helper DNS with the if local switching. When you do server side rendering of DNS front he node side, that needs to run in the node env to be compatible with next.js rendering. @isidroamv can you take a look at this?

**Comment by saleel** [comment]
This should be fixed now with the fix in `@zk-email/helpers` package.
