### ISSUE TITLE
Error when embeded 3'rd party

### ISSUE THREAD

**Issue by Hnng2011** [zkemail/proof-of-twitter#19]
I got error when using a SDK name Particle Network  with proof of twitter , everything okay except login with other evm wallet , I'm using the  Particle Auth with Rainbow Kit .

![image](https://github.com/zkemail/proof-of-twitter/assets/105967867/6428b32e-34ff-4fa6-b798-b3fd5249bd4b)
![image](https://github.com/zkemail/proof-of-twitter/assets/105967867/4c86dd01-5af1-4fa2-9de9-387da20281b0)

**Comment by Divide-By-0** [comment]
Hey, there seems to be a series of mistakes in your configuration between lit, vercel, content security policies, your new login SDK, and event listeners. Once you fix those issues, I recommend reposting if there's still a problem. This does not look like an issue with our website. I recommend 1) using your setup for login on a fresh create next app and letting us know if that works, and 2) using a different login provider on top of proof of Twitter.
