### ISSUE TITLE
Download fails

### ISSUE THREAD

**Issue by Divide-By-0** [zkemail/proof-of-twitter#8]
We are getting 403 forbidden on all of the files right now.

![telegram-cloud-photo-size-5-6062236018230277865-y](https://github.com/zkemail/proof-of-twitter/assets/4804438/e8dc5367-1c91-49fe-bfbd-c457bb256260)

**Comment by saleel** [comment]
✅  zkeys are now moved to GCP and https://twitter.prove.email/ is updated with new links.
